### ISSUE TITLE
`dry-run` folder creation

### ISSUE THREAD

**Issue by jckitch** [NSAPH-Data-Processing/global_geoboundaries#9]
If someone tests the pipeline with a `dry-run`, `downloader.py` creates corresponding output folders (which in theory it shouldn't in a dry run, right?). And then if someone goes to run the script for real, they need to set `overwrite=True` even though they haven't written anything to these folders.

**Comment by audiracmichelle** [comment]
closed in [b453c80](https://github.com/NSAPH-Data-Processing/global_geoboundaries/commit/b453c8047f0c7d61c33c04f17ddeef0a1cb2bb26)
